// Artist's Top Tracks

//Gives 10

id = '1gR0gsQYfi6joyO1dlp76N'

country = 'US'

OAuth Token = 'BQAAIlbbtbO_RmUfVsh0IJhDbj3iusqIRxK5LleNwO6kXQFecLOiAY4vyw8ZOd01KDe2NskTKiEaasYJjosTDUcccTc9Zt9Go-iUq6jE5FXYlLTRlVajwkABTyvDNQcZIBBODBS3XpgJYGZFcC8'

GET https://api.spotify.com/v1/artists/{id}/top-tracks

curl -X "GET" "https://api.spotify.com/v1/artists/1gR0gsQYfi6joyO1dlp76N/top-tracks?country=US" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer BQAAIlbbtbO_RmUfVsh0IJhDbj3iusqIRxK5LleNwO6kXQFecLOiAY4vyw8ZOd01KDe2NskTKiEaasYJjosTDUcccTc9Zt9Go-iUq6jE5FXYlLTRlVajwkABTyvDNQcZIBBODBS3XpgJYGZFcC8"


//Result:

{
  "tracks": [
    {
      "album": {
        "album_type": "album",
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1gR0gsQYfi6joyO1dlp76N"
            },
            "href": "https://api.spotify.com/v1/artists/1gR0gsQYfi6joyO1dlp76N",
            "id": "1gR0gsQYfi6joyO1dlp76N",
            "name": "Justice",
            "type": "artist",
            "uri": "spotify:artist:1gR0gsQYfi6joyO1dlp76N"
          }
        ],
        "available_markets": [
          "AD",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "RO",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/4GGazqHvuKwxBjWLFaJkDL"
        },
        "href": "https://api.spotify.com/v1/albums/4GGazqHvuKwxBjWLFaJkDL",
        "id": "4GGazqHvuKwxBjWLFaJkDL",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/12a94fe500df1758d81d27dabf76cf85896ebb38",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/6fd3d443e71f42095ccb43e9f214787c781e54af",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/7f77b5668ede4002bd73463222c6554ccfd463a4",
            "width": 64
          }
        ],
        "name": "Justice",
        "release_date": "2007-06-11",
        "release_date_precision": "day",
        "type": "album",
        "uri": "spotify:album:4GGazqHvuKwxBjWLFaJkDL"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/1gR0gsQYfi6joyO1dlp76N"
          },
          "href": "https://api.spotify.com/v1/artists/1gR0gsQYfi6joyO1dlp76N",
          "id": "1gR0gsQYfi6joyO1dlp76N",
          "name": "Justice",
          "type": "artist",
          "uri": "spotify:artist:1gR0gsQYfi6joyO1dlp76N"
        }
      ],
      "available_markets": [
        "AD",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IS",
        "IT",
        "JP",
        "LI",
        "LT",
        "LU",
        "LV",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "RO",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA"
      ],
      "disc_number": 1,
      "duration_ms": 242266,
      "explicit": false,
      "external_ids": {
        "isrc": "FR0NT0700420"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/33yAEqzKXexYM3WlOYtTfQ"
      },
      "href": "https://api.spotify.com/v1/tracks/33yAEqzKXexYM3WlOYtTfQ",
      "id": "33yAEqzKXexYM3WlOYtTfQ",
      "is_local": false,
      "name": "D.A.N.C.E",
      "popularity": 66,
      "preview_url": "https://p.scdn.co/mp3-preview/49f75305315925159a3eb9c9883f009a0b6d4267?cid=774b29d4f13844c495f206cafdad9c86",
      "track_number": 3,
      "type": "track",
      "uri": "spotify:track:33yAEqzKXexYM3WlOYtTfQ"
    },
    {
      "album": {
        "album_type": "single",
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1gR0gsQYfi6joyO1dlp76N"
            },
            "href": "https://api.spotify.com/v1/artists/1gR0gsQYfi6joyO1dlp76N",
            "id": "1gR0gsQYfi6joyO1dlp76N",
            "name": "Justice",
            "type": "artist",
            "uri": "spotify:artist:1gR0gsQYfi6joyO1dlp76N"
          }
        ],
        "available_markets": [
          "AD",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "RO",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/4bw1snvyLVGm7Hk5NtRxik"
        },
        "href": "https://api.spotify.com/v1/albums/4bw1snvyLVGm7Hk5NtRxik",
        "id": "4bw1snvyLVGm7Hk5NtRxik",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/5e7b6352f89e36df81f06157813213a7444ef145",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/401999683a32f2b7a639aaa9574b7eb0c92e364b",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/3ac3f7bfe9c86c5d3d587e429ba4d4ac71514846",
            "width": 64
          }
        ],
        "name": "Stop (WWW) [Radio Edit]",
        "release_date": "2018-05-07",
        "release_date_precision": "day",
        "type": "album",
        "uri": "spotify:album:4bw1snvyLVGm7Hk5NtRxik"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/1gR0gsQYfi6joyO1dlp76N"
          },
          "href": "https://api.spotify.com/v1/artists/1gR0gsQYfi6joyO1dlp76N",
          "id": "1gR0gsQYfi6joyO1dlp76N",
          "name": "Justice",
          "type": "artist",
          "uri": "spotify:artist:1gR0gsQYfi6joyO1dlp76N"
        }
      ],
      "available_markets": [
        "AD",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IS",
        "IT",
        "JP",
        "LI",
        "LT",
        "LU",
        "LV",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "RO",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA"
      ],
      "disc_number": 1,
      "duration_ms": 209826,
      "explicit": false,
      "external_ids": {
        "isrc": "FR8EU1800310"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/0Dx2JcexaaBU11URKp9Fc1"
      },
      "href": "https://api.spotify.com/v1/tracks/0Dx2JcexaaBU11URKp9Fc1",
      "id": "0Dx2JcexaaBU11URKp9Fc1",
      "is_local": false,
      "name": "Stop (WWW) - Radio Edit",
      "popularity": 59,
      "preview_url": "https://p.scdn.co/mp3-preview/762ad0df25d0e0d9dd902bc3de6e26c6c80087ad?cid=774b29d4f13844c495f206cafdad9c86",
      "track_number": 1,
      "type": "track",
      "uri": "spotify:track:0Dx2JcexaaBU11URKp9Fc1"
    },
    {
      "album": {
        "album_type": "album",
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1gR0gsQYfi6joyO1dlp76N"
            },
            "href": "https://api.spotify.com/v1/artists/1gR0gsQYfi6joyO1dlp76N",
            "id": "1gR0gsQYfi6joyO1dlp76N",
            "name": "Justice",
            "type": "artist",
            "uri": "spotify:artist:1gR0gsQYfi6joyO1dlp76N"
          }
        ],
        "available_markets": [
          "AD",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "RO",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/4GGazqHvuKwxBjWLFaJkDL"
        },
        "href": "https://api.spotify.com/v1/albums/4GGazqHvuKwxBjWLFaJkDL",
        "id": "4GGazqHvuKwxBjWLFaJkDL",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/12a94fe500df1758d81d27dabf76cf85896ebb38",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/6fd3d443e71f42095ccb43e9f214787c781e54af",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/7f77b5668ede4002bd73463222c6554ccfd463a4",
            "width": 64
          }
        ],
        "name": "Justice",
        "release_date": "2007-06-11",
        "release_date_precision": "day",
        "type": "album",
        "uri": "spotify:album:4GGazqHvuKwxBjWLFaJkDL"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/1gR0gsQYfi6joyO1dlp76N"
          },
          "href": "https://api.spotify.com/v1/artists/1gR0gsQYfi6joyO1dlp76N",
          "id": "1gR0gsQYfi6joyO1dlp76N",
          "name": "Justice",
          "type": "artist",
          "uri": "spotify:artist:1gR0gsQYfi6joyO1dlp76N"
        }
      ],
      "available_markets": [
        "AD",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IS",
        "IT",
        "JP",
        "LI",
        "LT",
        "LU",
        "LV",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "RO",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA"
      ],
      "disc_number": 1,
      "duration_ms": 234960,
      "explicit": false,
      "external_ids": {
        "isrc": "FR0NT0700300"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/4wSmqFg31t6LsQWtzYAJob"
      },
      "href": "https://api.spotify.com/v1/tracks/4wSmqFg31t6LsQWtzYAJob",
      "id": "4wSmqFg31t6LsQWtzYAJob",
      "is_local": false,
      "name": "Genesis",
      "popularity": 59,
      "preview_url": "https://p.scdn.co/mp3-preview/c93eb226b0227e538effb81c0b1d75d07cdb08c3?cid=774b29d4f13844c495f206cafdad9c86",
      "track_number": 1,
      "type": "track",
      "uri": "spotify:track:4wSmqFg31t6LsQWtzYAJob"
    },
    {
      "album": {
        "album_type": "album",
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1gR0gsQYfi6joyO1dlp76N"
            },
            "href": "https://api.spotify.com/v1/artists/1gR0gsQYfi6joyO1dlp76N",
            "id": "1gR0gsQYfi6joyO1dlp76N",
            "name": "Justice",
            "type": "artist",
            "uri": "spotify:artist:1gR0gsQYfi6joyO1dlp76N"
          }
        ],
        "available_markets": [
          "AD",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "RO",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/23EaoI8dXfDGfxF54sd1DP"
        },
        "href": "https://api.spotify.com/v1/albums/23EaoI8dXfDGfxF54sd1DP",
        "id": "23EaoI8dXfDGfxF54sd1DP",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/c164e386822d8e2cc42447d1073a9af34a6cf64a",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/10c82c2b333a083341bc9388f261691978ba517f",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/1d306c91e0204dc6a307cce3333ebe0f299a3ca7",
            "width": 64
          }
        ],
        "name": "Woman",
        "release_date": "2016-11-18",
        "release_date_precision": "day",
        "type": "album",
        "uri": "spotify:album:23EaoI8dXfDGfxF54sd1DP"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/1gR0gsQYfi6joyO1dlp76N"
          },
          "href": "https://api.spotify.com/v1/artists/1gR0gsQYfi6joyO1dlp76N",
          "id": "1gR0gsQYfi6joyO1dlp76N",
          "name": "Justice",
          "type": "artist",
          "uri": "spotify:artist:1gR0gsQYfi6joyO1dlp76N"
        }
      ],
      "available_markets": [
        "AD",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IS",
        "IT",
        "JP",
        "LI",
        "LT",
        "LU",
        "LV",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "RO",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA"
      ],
      "disc_number": 1,
      "duration_ms": 345303,
      "explicit": false,
      "external_ids": {
        "isrc": "FR9W11607807"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/5pqbHlHaVbkHJQlsAxhcZM"
      },
      "href": "https://api.spotify.com/v1/tracks/5pqbHlHaVbkHJQlsAxhcZM",
      "id": "5pqbHlHaVbkHJQlsAxhcZM",
      "is_local": false,
      "name": "Safe and Sound",
      "popularity": 57,
      "preview_url": "https://p.scdn.co/mp3-preview/b62087bd9584e65815a70a731070a82bae05b5db?cid=774b29d4f13844c495f206cafdad9c86",
      "track_number": 1,
      "type": "track",
      "uri": "spotify:track:5pqbHlHaVbkHJQlsAxhcZM"
    },
    {
      "album": {
        "album_type": "single",
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/0SwO7SWeDHJijQ3XNS7xEE"
            },
            "href": "https://api.spotify.com/v1/artists/0SwO7SWeDHJijQ3XNS7xEE",
            "id": "0SwO7SWeDHJijQ3XNS7xEE",
            "name": "MGMT",
            "type": "artist",
            "uri": "spotify:artist:0SwO7SWeDHJijQ3XNS7xEE"
          }
        ],
        "available_markets": [
          "AD",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "RO",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/6wqufLWm8D5CUPB9A11opq"
        },
        "href": "https://api.spotify.com/v1/albums/6wqufLWm8D5CUPB9A11opq",
        "id": "6wqufLWm8D5CUPB9A11opq",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/56c3f38a196ac92be77e837733ca3462eff866a6",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/f5a68a939bf5706a5cd5ebe8ffa452061a0a88bc",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/47233a91ecf150d2af42efee77e202f771ad5083",
            "width": 64
          }
        ],
        "name": "Electric Feel (Justice Remix)",
        "release_date": "2008-07-15",
        "release_date_precision": "day",
        "type": "album",
        "uri": "spotify:album:6wqufLWm8D5CUPB9A11opq"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/0SwO7SWeDHJijQ3XNS7xEE"
          },
          "href": "https://api.spotify.com/v1/artists/0SwO7SWeDHJijQ3XNS7xEE",
          "id": "0SwO7SWeDHJijQ3XNS7xEE",
          "name": "MGMT",
          "type": "artist",
          "uri": "spotify:artist:0SwO7SWeDHJijQ3XNS7xEE"
        },
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/1gR0gsQYfi6joyO1dlp76N"
          },
          "href": "https://api.spotify.com/v1/artists/1gR0gsQYfi6joyO1dlp76N",
          "id": "1gR0gsQYfi6joyO1dlp76N",
          "name": "Justice",
          "type": "artist",
          "uri": "spotify:artist:1gR0gsQYfi6joyO1dlp76N"
        }
      ],
      "available_markets": [
        "AD",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IS",
        "IT",
        "JP",
        "LI",
        "LT",
        "LU",
        "LV",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "RO",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA"
      ],
      "disc_number": 1,
      "duration_ms": 327386,
      "explicit": false,
      "external_ids": {
        "isrc": "USSM10802119"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/2eGHyarZyRvUgFI4d3G8GN"
      },
      "href": "https://api.spotify.com/v1/tracks/2eGHyarZyRvUgFI4d3G8GN",
      "id": "2eGHyarZyRvUgFI4d3G8GN",
      "is_local": false,
      "name": "Electric Feel - Justice Remix",
      "popularity": 55,
      "preview_url": "https://p.scdn.co/mp3-preview/2b03dd880b04ebb41c0d98460a323f6995bc7dc7?cid=774b29d4f13844c495f206cafdad9c86",
      "track_number": 1,
      "type": "track",
      "uri": "spotify:track:2eGHyarZyRvUgFI4d3G8GN"
    },
    {
      "album": {
        "album_type": "album",
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1gR0gsQYfi6joyO1dlp76N"
            },
            "href": "https://api.spotify.com/v1/artists/1gR0gsQYfi6joyO1dlp76N",
            "id": "1gR0gsQYfi6joyO1dlp76N",
            "name": "Justice",
            "type": "artist",
            "uri": "spotify:artist:1gR0gsQYfi6joyO1dlp76N"
          }
        ],
        "available_markets": [
          "AD",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "RO",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/23EaoI8dXfDGfxF54sd1DP"
        },
        "href": "https://api.spotify.com/v1/albums/23EaoI8dXfDGfxF54sd1DP",
        "id": "23EaoI8dXfDGfxF54sd1DP",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/c164e386822d8e2cc42447d1073a9af34a6cf64a",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/10c82c2b333a083341bc9388f261691978ba517f",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/1d306c91e0204dc6a307cce3333ebe0f299a3ca7",
            "width": 64
          }
        ],
        "name": "Woman",
        "release_date": "2016-11-18",
        "release_date_precision": "day",
        "type": "album",
        "uri": "spotify:album:23EaoI8dXfDGfxF54sd1DP"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/1gR0gsQYfi6joyO1dlp76N"
          },
          "href": "https://api.spotify.com/v1/artists/1gR0gsQYfi6joyO1dlp76N",
          "id": "1gR0gsQYfi6joyO1dlp76N",
          "name": "Justice",
          "type": "artist",
          "uri": "spotify:artist:1gR0gsQYfi6joyO1dlp76N"
        }
      ],
      "available_markets": [
        "AD",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IS",
        "IT",
        "JP",
        "LI",
        "LT",
        "LU",
        "LV",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "RO",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA"
      ],
      "disc_number": 1,
      "duration_ms": 334224,
      "explicit": false,
      "external_ids": {
        "isrc": "FR9W11614931"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/2X1XxaSRBqdJBcfyothrjT"
      },
      "href": "https://api.spotify.com/v1/tracks/2X1XxaSRBqdJBcfyothrjT",
      "id": "2X1XxaSRBqdJBcfyothrjT",
      "is_local": false,
      "name": "Fire",
      "popularity": 53,
      "preview_url": "https://p.scdn.co/mp3-preview/3261c61b32c8fc448a836b2d99c414ffd0730b05?cid=774b29d4f13844c495f206cafdad9c86",
      "track_number": 4,
      "type": "track",
      "uri": "spotify:track:2X1XxaSRBqdJBcfyothrjT"
    },
    {
      "album": {
        "album_type": "album",
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1gR0gsQYfi6joyO1dlp76N"
            },
            "href": "https://api.spotify.com/v1/artists/1gR0gsQYfi6joyO1dlp76N",
            "id": "1gR0gsQYfi6joyO1dlp76N",
            "name": "Justice",
            "type": "artist",
            "uri": "spotify:artist:1gR0gsQYfi6joyO1dlp76N"
          }
        ],
        "available_markets": [
          "AD",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "RO",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/23EaoI8dXfDGfxF54sd1DP"
        },
        "href": "https://api.spotify.com/v1/albums/23EaoI8dXfDGfxF54sd1DP",
        "id": "23EaoI8dXfDGfxF54sd1DP",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/c164e386822d8e2cc42447d1073a9af34a6cf64a",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/10c82c2b333a083341bc9388f261691978ba517f",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/1d306c91e0204dc6a307cce3333ebe0f299a3ca7",
            "width": 64
          }
        ],
        "name": "Woman",
        "release_date": "2016-11-18",
        "release_date_precision": "day",
        "type": "album",
        "uri": "spotify:album:23EaoI8dXfDGfxF54sd1DP"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/1gR0gsQYfi6joyO1dlp76N"
          },
          "href": "https://api.spotify.com/v1/artists/1gR0gsQYfi6joyO1dlp76N",
          "id": "1gR0gsQYfi6joyO1dlp76N",
          "name": "Justice",
          "type": "artist",
          "uri": "spotify:artist:1gR0gsQYfi6joyO1dlp76N"
        }
      ],
      "available_markets": [
        "AD",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IS",
        "IT",
        "JP",
        "LI",
        "LT",
        "LU",
        "LV",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "RO",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA"
      ],
      "disc_number": 1,
      "duration_ms": 297316,
      "explicit": false,
      "external_ids": {
        "isrc": "FR9W11614932"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/0WQbCSbujb6bSPVENrWYrl"
      },
      "href": "https://api.spotify.com/v1/tracks/0WQbCSbujb6bSPVENrWYrl",
      "id": "0WQbCSbujb6bSPVENrWYrl",
      "is_local": false,
      "name": "Stop",
      "popularity": 52,
      "preview_url": "https://p.scdn.co/mp3-preview/4aeb42bea3fced1c51bd33c5959e3cc77eee6b04?cid=774b29d4f13844c495f206cafdad9c86",
      "track_number": 5,
      "type": "track",
      "uri": "spotify:track:0WQbCSbujb6bSPVENrWYrl"
    },
    {
      "album": {
        "album_type": "single",
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1gR0gsQYfi6joyO1dlp76N"
            },
            "href": "https://api.spotify.com/v1/artists/1gR0gsQYfi6joyO1dlp76N",
            "id": "1gR0gsQYfi6joyO1dlp76N",
            "name": "Justice",
            "type": "artist",
            "uri": "spotify:artist:1gR0gsQYfi6joyO1dlp76N"
          }
        ],
        "available_markets": [
          "AD",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "RO",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/0Vt3GOtAqaBlyyaFVoSXhz"
        },
        "href": "https://api.spotify.com/v1/albums/0Vt3GOtAqaBlyyaFVoSXhz",
        "id": "0Vt3GOtAqaBlyyaFVoSXhz",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/d510ea876718741cdff3a621114c91911513a8e2",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/fba7bd4e11eaffb311318895142cc63ba0cbb097",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/d50a26fb6a8695bb42ad3e67826ffc98d4b80955",
            "width": 64
          }
        ],
        "name": "Civilization",
        "release_date": "2011-06-06",
        "release_date_precision": "day",
        "type": "album",
        "uri": "spotify:album:0Vt3GOtAqaBlyyaFVoSXhz"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/1gR0gsQYfi6joyO1dlp76N"
          },
          "href": "https://api.spotify.com/v1/artists/1gR0gsQYfi6joyO1dlp76N",
          "id": "1gR0gsQYfi6joyO1dlp76N",
          "name": "Justice",
          "type": "artist",
          "uri": "spotify:artist:1gR0gsQYfi6joyO1dlp76N"
        }
      ],
      "available_markets": [
        "AD",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IS",
        "IT",
        "JP",
        "LI",
        "LT",
        "LU",
        "LV",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "RO",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA"
      ],
      "disc_number": 1,
      "duration_ms": 250825,
      "explicit": false,
      "external_ids": {
        "isrc": "FR0NT1100370"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/3cn4e9MRXiUmDqTioimYBp"
      },
      "href": "https://api.spotify.com/v1/tracks/3cn4e9MRXiUmDqTioimYBp",
      "id": "3cn4e9MRXiUmDqTioimYBp",
      "is_local": false,
      "name": "Civilization",
      "popularity": 51,
      "preview_url": "https://p.scdn.co/mp3-preview/13a1020aae36cf5feebd9efed9e0c9e6f6ccb2ac?cid=774b29d4f13844c495f206cafdad9c86",
      "track_number": 1,
      "type": "track",
      "uri": "spotify:track:3cn4e9MRXiUmDqTioimYBp"
    },
    {
      "album": {
        "album_type": "album",
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1gR0gsQYfi6joyO1dlp76N"
            },
            "href": "https://api.spotify.com/v1/artists/1gR0gsQYfi6joyO1dlp76N",
            "id": "1gR0gsQYfi6joyO1dlp76N",
            "name": "Justice",
            "type": "artist",
            "uri": "spotify:artist:1gR0gsQYfi6joyO1dlp76N"
          }
        ],
        "available_markets": [
          "AD",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "RO",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/4GGazqHvuKwxBjWLFaJkDL"
        },
        "href": "https://api.spotify.com/v1/albums/4GGazqHvuKwxBjWLFaJkDL",
        "id": "4GGazqHvuKwxBjWLFaJkDL",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/12a94fe500df1758d81d27dabf76cf85896ebb38",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/6fd3d443e71f42095ccb43e9f214787c781e54af",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/7f77b5668ede4002bd73463222c6554ccfd463a4",
            "width": 64
          }
        ],
        "name": "Justice",
        "release_date": "2007-06-11",
        "release_date_precision": "day",
        "type": "album",
        "uri": "spotify:album:4GGazqHvuKwxBjWLFaJkDL"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/1gR0gsQYfi6joyO1dlp76N"
          },
          "href": "https://api.spotify.com/v1/artists/1gR0gsQYfi6joyO1dlp76N",
          "id": "1gR0gsQYfi6joyO1dlp76N",
          "name": "Justice",
          "type": "artist",
          "uri": "spotify:artist:1gR0gsQYfi6joyO1dlp76N"
        }
      ],
      "available_markets": [
        "AD",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IS",
        "IT",
        "JP",
        "LI",
        "LT",
        "LU",
        "LV",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "RO",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA"
      ],
      "disc_number": 1,
      "duration_ms": 200826,
      "explicit": false,
      "external_ids": {
        "isrc": "FR0NT0700320"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/2A3emhzbZo7eSvEUtAm3ZS"
      },
      "href": "https://api.spotify.com/v1/tracks/2A3emhzbZo7eSvEUtAm3ZS",
      "id": "2A3emhzbZo7eSvEUtAm3ZS",
      "is_local": false,
      "name": "Phantom Pt. II",
      "popularity": 51,
      "preview_url": "https://p.scdn.co/mp3-preview/dd19c2c8bca5588cc41b7cc8cdf8ad0a22098648?cid=774b29d4f13844c495f206cafdad9c86",
      "track_number": 6,
      "type": "track",
      "uri": "spotify:track:2A3emhzbZo7eSvEUtAm3ZS"
    },
    {
      "album": {
        "album_type": "single",
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1gR0gsQYfi6joyO1dlp76N"
            },
            "href": "https://api.spotify.com/v1/artists/1gR0gsQYfi6joyO1dlp76N",
            "id": "1gR0gsQYfi6joyO1dlp76N",
            "name": "Justice",
            "type": "artist",
            "uri": "spotify:artist:1gR0gsQYfi6joyO1dlp76N"
          }
        ],
        "available_markets": [
          "AD",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "RO",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "external_urls": {
          "spotify": "https://open.spotify.com/album/5bB2u4DtyaWvAdzaPEdmzM"
        },
        "href": "https://api.spotify.com/v1/albums/5bB2u4DtyaWvAdzaPEdmzM",
        "id": "5bB2u4DtyaWvAdzaPEdmzM",
        "images": [
          {
            "height": 640,
            "url": "https://i.scdn.co/image/f6c1301c5ee31d72e89d9df063487b7bbcde4b62",
            "width": 640
          },
          {
            "height": 300,
            "url": "https://i.scdn.co/image/62bc3ad9991d4e373c328030e9a706e2a24588e1",
            "width": 300
          },
          {
            "height": 64,
            "url": "https://i.scdn.co/image/eee1de65ca68960c0752d9b0cac50b678ce06b08",
            "width": 64
          }
        ],
        "name": "Pleasure (Live)",
        "release_date": "2017-07-21",
        "release_date_precision": "day",
        "type": "album",
        "uri": "spotify:album:5bB2u4DtyaWvAdzaPEdmzM"
      },
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/1gR0gsQYfi6joyO1dlp76N"
          },
          "href": "https://api.spotify.com/v1/artists/1gR0gsQYfi6joyO1dlp76N",
          "id": "1gR0gsQYfi6joyO1dlp76N",
          "name": "Justice",
          "type": "artist",
          "uri": "spotify:artist:1gR0gsQYfi6joyO1dlp76N"
        }
      ],
      "available_markets": [
        "AD",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "EC",
        "EE",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IS",
        "IT",
        "JP",
        "LI",
        "LT",
        "LU",
        "LV",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "PA",
        "PE",
        "PH",
        "PL",
        "PT",
        "PY",
        "RO",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA"
      ],
      "disc_number": 1,
      "duration_ms": 222000,
      "explicit": false,
      "external_ids": {
        "isrc": "FR8EU1700010"
      },
      "external_urls": {
        "spotify": "https://open.spotify.com/track/0EwVMQ9wHiFjEvioD85naI"
      },
      "href": "https://api.spotify.com/v1/tracks/0EwVMQ9wHiFjEvioD85naI",
      "id": "0EwVMQ9wHiFjEvioD85naI",
      "is_local": false,
      "name": "Pleasure (Live)",
      "popularity": 51,
      "preview_url": "https://p.scdn.co/mp3-preview/759d324b0c7e9ef2e533e124463d90a392359b42?cid=774b29d4f13844c495f206cafdad9c86",
      "track_number": 1,
      "type": "track",
      "uri": "spotify:track:0EwVMQ9wHiFjEvioD85naI"
    }
  ]
}